# Generated by Django 4.2.6 on 2023-10-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_post_rating_post_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_type',
            new_name='type',
        ),
    ]
