# Generated by Django 4.2.6 on 2023-10-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_post_type_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
