# Generated by Django 4.2.6 on 2023-10-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_category_name_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_rating',
            new_name='rating',
        ),
    ]
