# Generated by Django 4.2.6 on 2023-11-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_postcategory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subcribers',
            new_name='subscribers',
        ),
    ]
